services:
  - type: web
    name: portfolio-backend
    runtime: node
    region: oregon
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_TOKEN_ID
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: PORT
        value: 9001